<?xml version="1.0" encoding="utf-8"?>
<Database Name="ExamineDB" Class="ExamineDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=zhengyd;Initial Catalog=ExamineDB;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ExamineDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Examinee" Member="Examinee">
    <Type Name="Examinee">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Status" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="Examinee_OnlineExamine" Member="OnlineExamine" OtherKey="ExamineeID" Type="OnlineExamine" />
    </Type>
  </Table>
  <Table Name="dbo.OnlineExamine" Member="OnlineExamine">
    <Type Name="OnlineExamine">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExamineeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Score" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="OnlineExamine_ExamineeAnswer" Member="ExamineeAnswer" OtherKey="OnlineExamineID" Type="ExamineeAnswer" />
      <Association Name="Examinee_OnlineExamine" Member="Examinee" ThisKey="ExamineeID" Type="Examinee" IsForeignKey="true" />
      <Association Name="Subject_OnlineExamine" Member="Subject" ThisKey="SubjectID" Type="Subject" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Question" Member="Question">
    <Type Name="Question">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(2000)" CanBeNull="true" />
      <Column Name="Score" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Answer" Type="System.String" DbType="Char(20)" CanBeNull="true" />
      <Column Name="SubjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Question_Answer" Member="Answer1" OtherKey="QuestionID" Type="Answer" />
      <Association Name="Question_ExamineeAnswer" Member="ExamineeAnswer" OtherKey="QuestionID" Type="ExamineeAnswer" />
      <Association Name="Subject_Question" Member="Subject" ThisKey="SubjectID" Type="Subject" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Subject" Member="Subject">
    <Type Name="Subject">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Subject_OnlineExamine" Member="OnlineExamine" OtherKey="SubjectID" Type="OnlineExamine" />
      <Association Name="Subject_Question" Member="Question" OtherKey="SubjectID" Type="Question" />
    </Type>
  </Table>
  <Table Name="dbo.Answer" Member="Answer">
    <Type Name="Answer">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tag" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Column Name="Body" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="QuestionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Question_Answer" Member="Question" ThisKey="QuestionID" Type="Question" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AdminUser" Member="AdminUser">
    <Type Name="AdminUser">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ExamineeAnswer" Member="ExamineeAnswer">
    <Type Name="ExamineeAnswer">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OnlineExamineID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuestionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Answer" Type="System.String" DbType="Char(2)" CanBeNull="true" />
      <Association Name="OnlineExamine_ExamineeAnswer" Member="OnlineExamine" ThisKey="OnlineExamineID" Type="OnlineExamine" IsForeignKey="true" />
      <Association Name="Question_ExamineeAnswer" Member="Question" ThisKey="QuestionID" Type="Question" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.Pr_GetScores" Method="Pr_GetScores">
    <ElementType Name="Pr_GetScoresResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExamineeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SubjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Score" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SubjectName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>